### ISSUE TITLE
client run error

### ISSUE THREAD

**Issue by rexzhang2023** [SamurAIGPT/privateGPT#2]
(pgweb) rex@alienware17B:~/pgweb/privateGPT/client$ npm run dev

> privategpt@0.1.0 dev
> next dev

/home/rex/pgweb/privateGPT/client/node_modules/next/dist/cli/next-dev.js:256
            showAll: args["--show-all"] ?? false,
                                         ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.dev (/home/rex/pgweb/privateGPT/client/node_modules/next/dist/lib/commands.js:15:30)
    at Object.<anonymous> (/home/rex/pgweb/privateGPT/client/node_modules/next/dist/bin/next:150:28)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

**Comment by Anil-matcha** [comment]
Have you run 
npm install

before running npm run dev

**Comment by rexzhang2023** [comment]
yes ,I did

**Comment by Anil-matcha** [comment]
@rexzhang2023 Maybe your node version is not updated, you can update it and check

**Comment by rexzhang2023** [comment]
to which version? 14?

**Comment by rexzhang2023** [comment]
upgrade node to 14 ,and got this :
SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/home/rex/pgweb/privateGPT/client/node_modules/next/dist/telemetry/post-payload.js:17:20)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! privategpt@0.1.0 dev: `next dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the privategpt@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-05-26T09_08_26_601Z-debug.log

**Comment by Anil-matcha** [comment]
My node version is v18.16.0

So from what you mentioned, you must be using an old version

**Comment by thomaskant** [comment]
Hello @rexzhang2023!

I have not tried the project myself, but from my experience after upgrading your node version and still get an error try to remove the `node_modules` folder and running `npm install` again :)

**Comment by Anil-matcha** [comment]
Closing due to inactivity

**Comment by sucat1997** [comment]
It's helpful, I really appreciate it
