### ISSUE TITLE
chromadb.errors.NoIndexException

### ISSUE THREAD

**Issue by askucher** [SamurAIGPT/privateGPT#21]
I have downloaded a model
Uploaded a bitcoin white paper

Asked : `What is that paper about` and got 

```
Using embedded DuckDB with persistence: data will be stored in: db/
[2023-05-29 00:45:56,320] ERROR in app: Exception on /get_answer [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "privateGPT.py", line 146, in get_answer
    res = qa(query)
  File "/usr/local/lib/python3.8/dist-packages/langchain/chains/base.py", line 140, in __call__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/langchain/chains/base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/usr/local/lib/python3.8/dist-packages/langchain/chains/retrieval_qa/base.py", line 119, in _call
    docs = self._get_docs(question)
  File "/usr/local/lib/python3.8/dist-packages/langchain/chains/retrieval_qa/base.py", line 181, in _get_docs
    return self.retriever.get_relevant_documents(question)
  File "/usr/local/lib/python3.8/dist-packages/langchain/vectorstores/base.py", line 377, in get_relevant_documents
    docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/langchain/vectorstores/chroma.py", line 182, in similarity_search
    docs_and_scores = self.similarity_search_with_score(query, k, filter=filter)
  File "/usr/local/lib/python3.8/dist-packages/langchain/vectorstores/chroma.py", line 229, in similarity_search_with_score
    results = self.__query_collection(
  File "/usr/local/lib/python3.8/dist-packages/langchain/utils.py", line 52, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/langchain/vectorstores/chroma.py", line 121, in __query_collection
    return self._collection.query(
  File "/usr/local/lib/python3.8/dist-packages/chromadb/api/models/Collection.py", line 227, in query
    return self._client._query(
  File "/usr/local/lib/python3.8/dist-packages/chromadb/api/local.py", line 437, in _query
    uuids, distances = self._db.get_nearest_neighbors(
  File "/usr/local/lib/python3.8/dist-packages/chromadb/db/clickhouse.py", line 585, in get_nearest_neighbors
    uuids, distances = index.get_nearest_neighbors(embeddings, n_results, ids)
  File "/usr/local/lib/python3.8/dist-packages/chromadb/db/index/hnswlib.py", line 240, in get_nearest_neighbors
    raise NoIndexException(
chromadb.errors.NoIndexException: Index not found, please create an instance before querying
79.140.150.138 - - [29/May/2023 00:45:56] "POST /get_answer HTTP/1.1" 500 -
root@ns521942:/home/ubuntu/privateGPT/client/components# 

```

**Comment by askucher** [comment]
Forgot to click inject
