### ISSUE TITLE
I want push problem about client

### ISSUE THREAD

**Issue by canylee** [SamurAIGPT/privateGPT#5]
I updated your code about client when upload file function error.
This code updated:

const handleFileChange = (event) => {
    if (event.target.files && event.target.files.length > 0) {
      setSelectedFile(event.target.files[0]);
    }
    
  };

Please update your code. Thanks.

**Comment by Anil-matcha** [comment]
What error you are facing ? Please mention

**Comment by swapatel06** [comment]
Hi i'm facing the same issue while Uploading any document from the Web UI

Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading '0')

Source
components/ConfigSideNav.js (52:25) @ handleFileChange
  50 | 
  51 | const handleFileChange = (event) => {
> 52 |   if(event.target.file[0]!=null){
     |                       ^
  53 |     setSelectedFile(event.target.files[0]);
  54 |   }
  55 |

**Comment by Anil-matcha** [comment]
Checking the issue, meanwhile you can just put your documents in the source_documents folder in client and then click on ingest button from the UI as a workaround

**Comment by canylee** [comment]
> Hi i'm facing the same issue while Uploading any document from the Web UI
> 
> Unhandled Runtime Error TypeError: Cannot read properties of undefined (reading '0')
> 
> Source components/ConfigSideNav.js (52:25) @ handleFileChange 50 | 51 | const handleFileChange = (event) => {
> 
> > 52 |   if(event.target.file[0]!=null){
> > |                       ^
> > 53 |     setSelectedFile(event.target.files[0]);
> > 54 |   }
> > 55 |

You update it with this code and run it again:
const handleFileChange = (event) => {
if (event.target.files && event.target.files.length > 0) {
setSelectedFile(event.target.files[0]);
}

};

**Comment by swapatel06** [comment]
I've put my documents in the source_documents folder in the client as well as the server folder and then clicking on ingest button generates a validation error on the server terminal.

127.0.0.1 - - [26/May/2023 15:30:38] "GET /ingest HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/code/alchemy/conda/privateGPT/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/code/alchemy/conda/privateGPT/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/code/alchemy/conda/privateGPT/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/code/alchemy/conda/privateGPT/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/code/alchemy/conda/privateGPT/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/code/alchemy/conda/privateGPT/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/code/alchemy/conda/privateGPT/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/code/alchemy/conda/privateGPT/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/code/pipeline_users/swapnil_work/Packages/privateGPT-web/server/privateGPT.py", line 128, in ingest_data
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
  File "/code/alchemy/conda/privateGPT/lib/python3.10/site-packages/langchain/embeddings/huggingface.py", line 44, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for HuggingFaceEmbeddings
model_name
  none is not an allowed value (type=type_error.none.not_allowed)

**Comment by Anil-matcha** [comment]
@canylee @swapatel06 Have added a fix now for the file upload issue

**Comment by Anil-matcha** [comment]
@swapatel06 Looks like it is not picking the environment variable for hugging face model. Please check if you have taken the latest pull. EMBEDDINGS_MODEL_NAME is being shown None but ideally it should be loaded from .env file

**Comment by swapatel06** [comment]
Hi @Anil-matcha these things are fixed now i still have an error getting the response .. I'll generate another thread for it
